export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_FEEDS_START = 'FETCH_FEEDS_START';
export const FETCH_FEEDS_COMPLETED = 'FETCH_FEEDS_COMPLETED';
export const CATEGORY_FILTER_SELECTED = "CATEGORY_FILTER_SELECTED";
export const COUNTRY_FILTER_SELECTED = "COUNTRY_FILTER_SELECTED";
export const REMOVE_COUNTRY_FILTER = "REMOVE_COUNTRY_FILTER";
export const REMOVE_CATEGORY_FILTER = "REMOVE_CATEGORY_FILTER";
export const REFRESH_FEEDS = "REFRESH_FEEDS";